/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javafx.project;

import io.github.palexdev.materialfx.css.themes.MFXThemeManager;
import io.github.palexdev.materialfx.css.themes.Themes;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

import javafx.project.panels.MainLogin;
import javafx.project.database.Session;

public class App extends Application {
    private Scene scene;
    private Stage stage;
    private Pane root;
    private Session session;

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        stage = primaryStage;
        root = new Pane();
        session = Session.getInstance();

        MainLogin login_layout = new MainLogin(stage);
        root.getChildren().add(login_layout);

        scene = new Scene(root);

        MFXThemeManager.addOn(scene, Themes.DEFAULT, Themes.LEGACY);

        stage.setScene(scene);

        stage.centerOnScreen();
        stage.setResizable(false);

        System.out.println(session.isSetTerm());

        if (session.isSetTerm()) {
            stage.close();
        } else {
            stage.show();
        }
    }
}
