/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javafx.project;

import io.github.palexdev.materialfx.css.themes.MFXThemeManager;
import io.github.palexdev.materialfx.css.themes.Themes;
import javafx.application.Application;
import javafx.stage.Stage;
import javafx.scene.Scene;
import javafx.scene.layout.AnchorPane;
import javafx.project.panels.MainLogin;

public class App extends Application {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        MainLogin login_layout = new MainLogin();
        AnchorPane root = new AnchorPane();
        root.getChildren().add(login_layout);

        Scene scene = new Scene(root);
        MFXThemeManager.addOn(scene, Themes.DEFAULT, Themes.LEGACY);

        primaryStage.centerOnScreen();
        primaryStage.setTitle(getGreeting());
        primaryStage.setScene(scene);
        primaryStage.show();
    }
}
