/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javafx.project;

import io.github.palexdev.materialfx.css.themes.MFXThemeManager;
import io.github.palexdev.materialfx.css.themes.Themes;
import javafx.application.Application;
import javafx.project.panels.MainLogin;
import javafx.scene.Scene;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

public class App extends Application {
    protected Scene scene;
    protected Stage stage;

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        stage = primaryStage;

        MainLogin login_layout = new MainLogin(stage);
        Pane root = new Pane();
        root.getChildren().add(login_layout);

        scene = new Scene(root);

        MFXThemeManager.addOn(scene, Themes.DEFAULT, Themes.LEGACY);

        stage.setScene(scene);

        stage.centerOnScreen();
        stage.setResizable(false);
        stage.show();
    }
}
