/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javafx.project;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasMain() {
        assertNotNull(new App());
    }
}
