/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javafx.project;

import javafx.project.components.ImgIcon;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void hasHashCode() {
        assertNotNull(new App().hashCode());
    }

    @Test
    void hasImage() {
        ImgIcon icon = new ImgIcon("./img/user.png");
        assertNotNull(icon);
    }
}
